
export const ADD_POST = 'ADD_POST'

export const CREATE_BOARD = 'CREATE_BOARD'
export const CREATING_BOARD = 'CREATING_BOARD'
export const CREATED_BOARD = 'CREATED_BOARD'

export const UPDATE_BOARD = 'UPDATE_BOARD'

export const BOARD_ERROR = 'BOARD_ERROR'

export const ORBITDB_WRITE = 'ORBITDB_WRITE'
export const ORBITDB_REPLICATED = 'ORBITDB_REPLICATED'