
export const ADD_POST = 'ADD_POST'
export const UPDATE_BOARD_METADATA = 'UPDATE_BOARD_METADATA'

export const OPEN_BOARD = 'OPEN_BOARD'
export const OPENED_BOARD = 'OPENED_BOARD'
export const CLOSE_BOARD = 'CLOSE_BOARD'

export const UPDATE_BOARD = 'UPDATE_BOARD'

export const ORBITDB_WRITE = 'ORBITDB_WRITE'

export const ORBITDB_REPLICATE = 'ORBITDB_REPLICATE'
export const ORBITDB_REPLICATE_PROGRESS = 'ORBITDB_REPLICATE_PROGRESS'
export const ORBITDB_REPLICATED = 'ORBITDB_REPLICATED'

export const ERROR = 'ERROR'